--- #YAML:1.0
meta-spec:
  version: 1.2
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
name: RDF-Base
abstract: An RDF framework for Perl.
author: 'Gregory Todd Williams <gwilliams@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0.61
distribution_type: module
generated_by: Module::Install version 0.630
license: perl
no_index:
  directory:
    - inc
    - t
requires:
  Module::Pluggable: 0
  URI: 0
  version: 0
version: 0.001002
