author: 'Gregory Todd Williams <gwilliams@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0.61
distribution_type: module
generated_by: Module::Install version 0.630
license: perl
module_name: RDF::Base
name: RDF-Base
no_index:
  directory:
    - inc
    - t
requires:
  Module::Pluggable: 0
  URI: 0
  version: 0
version: !!perl/hash:version
  qv: 1
  version:
    - 0
    - 0
    - 1
