--- #YAML:1.0
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
name: RDF-LinkedData-Apache
version: 0.001
abstract: A mod_perl handler class for serving RDF as linked data.
author:
  - Gregory Todd Williams <gwilliams@cpan.org>
build_requires:
  Test::Exception: 0
  Test::MockObject: 0
  Test::More: 0.61
  File::Temp: 0
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
no_index:
  directory:
    - inc
    - t
requires:
  Apache2::Const: 0
  Apache2::Request: 0
  Apache2::RequestRec: 0
  Apache2::RequestUtil: 0
  Error: 0
  HTTP::Negotiate: 0
  RDF::Trine: 0.114
  Scalar::Util: 0
  URI::Escape: 0
resources:
  repository: http://github.com/kasei/perlrdf/
