# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RDF-Trine
version_from: lib/RDF/Trine.pm
installdirs:  site
author:
  - Gregory Todd Williams <gwilliams@cpan.org>
build_requires:
  Test::JSON: 0
  Test::More: 0.61
  Test::Exception: 0
recommends:
  RDF::Redland: 1
  RDF::Core: 0
requires:
    Bloom::Filter:                 0
    DBI:                           0
    DBD::SQLite                    1.14
    Digest::MD5:                   0
    Error:                         0
    JSON:                          2
    LWP::UserAgent:                0
    List::MoreUtils:               0
    List::Util:                    0
    Math::BigInt:                  0
    Scalar::Util:                  0
    Test::More:                    0
    Unicode::Escape:               0
    URI:                           0
    XML::CommonNS:                 0.04
    XML::Namespace:                0
    XML::Twig:                     0
license: perl
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
no_index:
  directory:
    - inc
    - t
