--- #YAML:1.0
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
name: RDF-SPARQLResults
version: 1.000
abstract: Stream (iterator) class for SPARQL query results.
author:
  - Gregory Todd Williams <gwilliams@cpan.org>
build_requires:
  Test::JSON: 0
  Test::More: 0.61
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
no_index:
  directory:
    - inc
    - t
recommends:
  RDF::Redland: 1
  RDF::Core: 0
requires:
  JSON: 0
