--- #YAML:1.0
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
name:         RDF-Trine-Store-Hexastore
version: 0.100
author:
  - Gregory Todd Williams <gwilliams@cpan.org>
build_requires:
  Test::JSON: 0
  Test::More: 0.61
  Test::Exception: 0
requires:
    RDF::Trine:                    0.109
    LWP::UserAgent:                0
    List::MoreUtils:               0
    List::Util:                    0
    Log::Log4perl:                 0
    Scalar::Util:                  0
license: perl
distribution_type: module
generated_by: Module::Install version 0.63
no_index:
  directory:
    - inc
    - t
resources:
  homepage: http://kasei.us/code/rdf-trine/
  Repository: http://github.com/kasei/perlrdf/
